trigger:
  branches:
    include:
      - main

pool:
  name: 'Docker-App'

variables:
  imageName: 'mirzzie/docker-app'      # Docker Hub repository
  containerName: 'sampleapp'           # Name of the Docker container on AWS
  serverUser: 'ubuntu'                 # SSH username for AWS server
  serverIp: $(AWS)       # AWS server IP address
  privateKey: $(Key)         # Private key for SSH authentication (stored securely in pipeline variables)

stages:
  - stage: Build
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            inputs:
              command: build
              repository: $(imageName)
              Dockerfile: '**/Dockerfile'
              tags: |
                $(Build.BuildId)
          - task: Docker@2
            inputs:
              command: push
              repository: $(imageName)
              tags: |
                $(Build.BuildId)

  - stage: Deploy
    displayName: 'Deploy to AWS Server'
    jobs:
      - job: Deploy
        steps:
          - script: |
              echo "Deploying to AWS Server..."
              # Create SSH key file
              echo "$(privateKey)" > ~/.ssh/aws_key
              chmod 600 ~/.ssh/aws_key

              # SSH into the server and pull the latest Docker image, then restart container
              ssh -i ~/.ssh/aws_key $(serverUser)@$(serverIp) << 'EOF'
                docker stop $(containerName) || true
                docker rm $(containerName) || true
                docker pull $(imageName):$(Build.BuildId)
                docker run -d --name $(containerName) -p 80:80 $(imageName):$(Build.BuildId)
              EOF
            displayName: 'Deploy Docker Container to AWS'

