trigger:
  branches:
    include:
      - main

pool:
  name: 'Docker-App'

variables:
  imageName: 'mirzzie/docker-app'
  containerName: 'sampleapp'
  serverUser: 'ubuntu'
  dockerServerIp: '13.203.78.251'
  pipelineServerIp: '65.1.94.55'
  privateKey: '$(Key)'

stages:
  - stage: Build
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'DockerRegistry'
              command: build
              repository: $(imageName)
              Dockerfile: '**/Dockerfile'
              tags: |
                $(Build.BuildId)

          - task: Docker@2
            inputs:
              containerRegistry: 'DockerHub'
              command: push
              repository: $(imageName)
              tags: |
                $(Build.BuildId)

  - stage: Deploy
    displayName: 'Deploy to AWS Docker Application EC2'
    jobs:
      - job: Deploy
        steps:
          - script: |
              echo "Deploying to AWS Docker Application Server..."
              
              # Save private key with correct permissions
              echo -e "${privateKey//\\n/$'\n'}" > ~/.ssh/aws_key
              chmod 600 ~/.ssh/aws_key

              # Corrected ssh-keyscan syntax
              ssh-keyscan -H $dockerServerIp >> ~/.ssh/known_hosts

              # Deploying Docker container on AWS
              ssh -i ~/.ssh/aws_key $serverUser@$dockerServerIp << EOF
                docker stop $containerName || true
                docker rm $containerName || true
                docker pull $imageName:$Build_BuildId
                docker run -d --name $containerName -p 80:80 $imageName:$Build_BuildId
              EOF
            displayName: 'Deploy Docker Container to AWS Docker Application EC2'
